nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 1 --reward-shift -1.0 2>&1 | tee logs/Push-1-1.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 2 --reward-shift -1.0 2>&1 | tee logs/Push-1-2.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 3 --reward-shift -1.0 2>&1 | tee logs/Push-1-3.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 4 --reward-shift -1.0 2>&1 | tee logs/Push-1-4.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 1 --reward-shift -0.5 2>&1 | tee logs/Push-0.5-1.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 2 --reward-shift -0.5 2>&1 | tee logs/Push-0.5-2.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 3 --reward-shift -0.5 2>&1 | tee logs/Push-0.5-3.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 4 --reward-shift -0.5 2>&1 | tee logs/Push-0.5-4.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 1 --reward-shift 1.0 2>&1 | tee logs/Push+1-1.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 2 --reward-shift 1.0 2>&1 | tee logs/Push+1-2.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 3 --reward-shift 1.0 2>&1 | tee logs/Push+1-3.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 4 --reward-shift 1.0 2>&1 | tee logs/Push+1-4.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 1 --reward-shift 0.5 2>&1 | tee logs/Push+0.5-1.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 2 --reward-shift 0.5 2>&1 | tee logs/Push+0.5-2.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 3 --reward-shift 0.5 2>&1 | tee logs/Push+0.5-3.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 4 --reward-shift 0.5 2>&1 | tee logs/Push+0.5-4.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 1 --reward-shift 0.0 2>&1 | tee logs/Push+0-1.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 2 --reward-shift 0.0 2>&1 | tee logs/Push+0-2.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 3 --reward-shift 0.0 2>&1 | tee logs/Push+0-3.log &
nohup mpirun -np 8 python -u train.py --env-name='FetchPush-v1' --n-epochs 50 --n-cycles=10 --seed 4 --reward-shift 0.0 2>&1 | tee logs/Push+0-4.log &